# Generated by Django 5.0.3 on 2025-07-26 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_started', models.DateTimeField()),
                ('date_time_ended', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_recognition_confidence', models.FloatField()),
                ('bounding_box', models.JSONField()),
                ('coco_keypoints', models.JSONField()),
                ('estimated_longitude', models.FloatField(blank=True, default=0.0, null=True)),
                ('estimated_latitude', models.FloatField(blank=True, default=0.0, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.mission')),
            ],
        ),
    ]
